run: zad3.c pid.c
	gcc -Wall zad3.c -o zad3
	gcc -Wall pid.c -o pid
	./zad3 2000 1
clean:
	rm zad3
	rm pid

runb: zad3b.c pid.c
	gcc -Wall zad3b.c -o zad3b
	gcc -Wall pid.c -o pid
	./zad3b 20 9 2

cleanb:
	rm pid
	rm zad3b
	
